name: Build LaTeX

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full python3-pygments

    - name: Compile .tex files to PDFs
      run: |
        mkdir -p output
        for texfile in $(find . -name '*.tex'); do
          filename=$(basename "$texfile" .tex)
          dir=$(dirname "$texfile")
          pdflatex -shell-escape -output-directory=output "$texfile" || true
          # Optional: Run multiple times for references etc.
          pdflatex -shell-escape -output-directory=output "$texfile" || true
        done

    - name: Upload PDFs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-artifacts
        path: output/*.pdf
