name: Build LaTeX

on:
  push:
    paths:
      - '**.tex'
      - '**.sty'
      - '**.cls'
      - '**.bib'
      - .github/workflows/latex.yml
  pull_request:
    paths:
      - '**.tex'
      - '**.sty'
      - '**.cls'
      - '**.bib'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install TeX Live and Python packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-luatex \
            texlive-xetex \
            texlive-science \
            latexmk \
            python3-pip
          pip3 install pygments

      - name: Compile LaTeX (slides.tex)
        run: |
          latexmk -pdf -shell-escape -interaction=nonstopmode slides.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: slides-pdf
          path: slides.pdf
